# Generated by Django 5.0.1 on 2024-02-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_order_customtaxsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippingCostSent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingCostVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingCost',
            field=models.IntegerField(default=-1),
        ),
    ]
