# Generated by Django 5.0.1 on 2024-02-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_order_orderrecieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billsOfLading',
            field=models.FileField(blank=True, null=True, upload_to='billsOfLading/'),
        ),
    ]
