# Generated by Django 5.0.1 on 2024-02-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_order_billsoflading'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customDocumentation',
            field=models.FileField(blank=True, null=True, upload_to='customDocumentation/'),
        ),
        migrations.AddField(
            model_name='order',
            name='exportDeclaration',
            field=models.FileField(blank=True, null=True, upload_to='exportDeclaration/'),
        ),
    ]
