# Generated by Django 5.0.1 on 2024-02-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_order_customdocumentation_order_exportdeclaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippingManifest',
            field=models.FileField(blank=True, null=True, upload_to='shippingManifest/'),
        ),
    ]
