# Generated by Django 5.0.1 on 2024-02-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customauthority',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portauthority',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingcompany',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
