# Generated by Django 5.0.1 on 2024-02-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
        ('signup', '0002_alter_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Order Placed', max_length=50)),
                ('address', models.CharField(default='', max_length=100)),
                ('diagram', models.FileField(blank=True, null=True, upload_to='diagrams/')),
                ('total', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.product')),
            ],
        ),
    ]
