# Generated by Django 5.0.1 on 2024-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_order_oilreqsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='excelSheet',
            field=models.FileField(blank=True, null=True, upload_to='excelSheets/'),
        ),
    ]
