# Generated by Django 5.0.1 on 2024-02-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_order_excelsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipReqSent',
            field=models.BooleanField(default=False),
        ),
    ]
