# Generated by Django 5.0.1 on 2024-02-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_order_shipreqsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customReqSent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='customTax',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingCost',
            field=models.IntegerField(default=0),
        ),
    ]
