# Generated by Django 5.0.1 on 2024-02-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_order_customreqsent_order_customtax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customTaxSent',
            field=models.BooleanField(default=False),
        ),
    ]
