# Generated by Django 5.0.1 on 2024-02-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_order_shippingcostsent_order_shippingcostverified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tankerDispatched',
            field=models.BooleanField(default=False),
        ),
    ]
