# Generated by Django 5.0.1 on 2024-02-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_order_tankerdispatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderRecieved',
            field=models.BooleanField(default=False),
        ),
    ]
