# Generated by Django 5.0.1 on 2024-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_order_sealcontainernumber_order_vesselinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tankPressure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('toGoMt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
