# Generated by Django 5.0.1 on 2024-02-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_excelsheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='excelSheet',
        ),
        migrations.AddField(
            model_name='excelsheet',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.order'),
        ),
    ]
